import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ViewTransitions } from "next-view-transitions";
import Cursor from "@/components/Cursor";


const dmSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" className="">
        <body
          className={`${dmSans.className} bg-neutral-100 dark:bg-black antialiased  selection:bg-neutral-900 selection:text-neutral-300 relative divide-y-1`}
        >
          <Cursor/>
          <Navbar />

          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
