import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import { ViewTransitions } from "next-view-transitions";
import Cursor from "@/components/Cursor";
import { Toaster } from "sonner";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en" className="">
        <body
          className={` bg-neutral-100 
            
          dark:bg-black antialiased  selection:bg-neutral-900 selection:text-neutral-300 dark:selection:bg-neutral-50 dark:selection:text-neutral-800 relative `}
        >
          <Toaster position="top-center"/>
          <Cursor/>
          <Navbar />

          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
